= Red Hat OpenShift IPI Installation
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2024-03
// Metadata
:description: This repository explores the basics of OpenShift IPI installations.
:keywords: openshift, red hat, installation, ipi
// Create TOC wherever needed
:toc:
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: docs/images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]
// End: Enable admonition icons

This repository explores the basics of OpenShift IPI installations.

== Choose your installation method

There are three installation models of Red Hat OpenShift, *UPI* for enterprise deployments, *IPI* for small deployments, and *ABI* oriented to air-gapped and restricted environments.

* *Installer-Provisioned Infrastructure* (IPI) is one of the most straightforward installation methods. It's suitable for users who want a guided, automated installation experience. In IPI, OpenShift provisions infrastructure including virtual machines or physical hardware. The recommendation is to call this installation method [.underline]#Full-stack Automation#.
* *Agent Based Installer* (ABI) comprises a bootable ISO that contains the Assisted discovery agent and the Assisted Service. Agent-based installation is a subcommand of the OpenShift installer. It generates a bootable ISO image containing all of the assets required to deploy an OpenShift cluster.
* *User-Provisioned Infrastructure* (UPI) is a flexible installation method for users who prefer to manage their own infrastructure. With UPI, users are responsible for provisioning virtual machines, storage, and networking components such as a load balancer. The recommendation is to call this installation method [.underline]#"Pre-existing Infrastructure"#.

In this repository, we will explore the benefit of IPI installation in bare-metal environments.


== Infrastructure

This section leverages `kcli` to create the VMs that will simulate the OCP nodes in which we will install OpenShift using the IPI installation method. It is important that you check these links before installing the plan:

* `kcli` https://kcli.readthedocs.io/en/latest[documentation].
* `kcli` https://github.com/karmab/kcli-openshift4-baremetal/tree/main[OCP 4 baremetal plan].
* `kcli` https://ocp-baremetal-ipi-lab.readthedocs.io/en/latest/#[lab to understand its basics].

Then, just execute the following command to deploy your infrastructure:

[source, bash]
----
kcli create plan ocp4 \
    -f kcli-openshift4-baremetal/kcli_plan_infra.yml \
    --paramfile ocp-ipi-installation/infrastructure/parameters.yml 
----

You can see the created VMs with the following command:

[source, bash]
----
$ kcli list vm

----




== Prerequisites


=== Install binaries

* `oc`. Add bash completion with:
    ** `sudo bash -c 'oc completion bash > /etc/bash_completion.d/openshift'`
* `openshift-install`. Add bash completion with:
    ** `sudo bash -c 'openshift-install completion bash > /etc/bash_completion.d/openshift-install'`.
* `butane`. Check this https://docs.openshift.com/container-platform/4.15/installing/install_config/installing-customizing.html#installation-special-config-butane_installing-customizing[link] for more information.


=== DNS Configuration

By default, you might configure the centralized DNS in your department. In this case, we will deploy a cluster in a lab environment with no access to centralized DNS. For that reason, we will configure our https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_networking_infrastructure_services/assembly_setting-up-and-configuring-a-bind-dns-server_networking-infrastructure-services[BIND DNS server]. BIND is a feature-rich DNS server that is fully compliant with the Internet Engineering Task Force (IETF) DNS standards and draft standards.

First, install the bind RPM packages:

[source, bash]
----
sudo dnf install bind bind-utils
----

Second, 




=== Quay Registry (If disconnected)



=== Kubeconfig and pull secret




=== Mirror container images







== Installation


openshift-install explain installconfig



== Postinstall


=== Update API and Ingress certificates

NOTE: Check if API is needed.


=== Authentication and authorization



NOTE: Now, you can disable `kubeadmin`.

NOTE: Now, you can configure LDAP group sync CronJob.


=== Infrastructure-dedicated nodes




== Useful resources





